apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://github.com/fsequeira1/gitops-istio
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/ 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: GitRepository
        name: flagger
  interval: 1h0m0s
  releaseName: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
    includeLabelPrefix: app
    istio:
      kubeconfig:
        secretName: ""
        key: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-grafana
  namespace: istio-system
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 1h0m0s
  releaseName: flagger-grafana
  values:
    url: http://prometheus.istio-system:9090
